=== RegulEsteban/extension_registry/entry-schema.json
{
  "id": "http://example.com",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Schema for an entry in the Open Contracting Extension Registry",
  "description": "Schema for an entry.json file pointing to the location of the extension.",
  "type": "object",
  "required": [
    "active",
    "category",
    "core",
    "description",
    "documentationUrl",
    "name",
    "url"
  ],
  "additionalProperties": false,
  "properties": {
    "active": {
      "title": "Active",
      "description": "Extension active/inactive status.",
      "type": "boolean"
    },
    "category": {
      "title": "Category",
      "description": "Part of the docs the extensions appears in.",
      "type": "string"
    },
    "core": {
      "title": "Core extension",
      "description": "Whether the extension is a core extension documented in the main docs.",
      "type": "boolean"
    },
    "dependencies": {
      "title": "Dependencies",
      "description": "Extensions this extension depends on.",
      "type": "array",
      "items":{
        "type": "string",
        "format": "uri",
        "pattern": "^.+/extension.json"
      }
    },
    "description": {
      "title": "Description",
      "description": "Description of the extensions as an object with keys being language codes (ISO 639-1) and values the description in that language.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^(ad|ae|af|ag|ai|al|am|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bl|bm|bn|bo|bq|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cu|cv|cw|cx|cy|cz|de|dj|dk|dm|do|dz|ec|ee|eg|eh|en|er|es|et|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mf|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sk|sl|sm|sn|so|sr|ss|st|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tr|tt|tv|tw|tz|ua|ug|um|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|za|zm|zw)$": {
          "type": "string"
        }
      }
    },
    "documentationUrl": {
      "title": "Documentation URL" ,
      "description": "Location of the documentation for the extension as an object with keys being language codes (ISO 639-1) and values the url of the documentation in that language.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^(ad|ae|af|ag|ai|al|am|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bl|bm|bn|bo|bq|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cu|cv|cw|cx|cy|cz|de|dj|dk|dm|do|dz|ec|ee|eg|eh|en|er|es|et|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mf|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sk|sl|sm|sn|so|sr|ss|st|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tr|tt|tv|tw|tz|ua|ug|um|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|za|zm|zw)$": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "name": {
      "title": "Name",
      "description": "Name of the extension as an object with keys being language codes (ISO 639-1) and values the name in that language",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^(ad|ae|af|ag|ai|al|am|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bl|bm|bn|bo|bq|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cu|cv|cw|cx|cy|cz|de|dj|dk|dm|do|dz|ec|ee|eg|eh|en|er|es|et|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mf|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sk|sl|sm|sn|so|sr|ss|st|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tr|tt|tv|tw|tz|ua|ug|um|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|za|zm|zw)$": {
          "type": "string"
        }
      }
    },
    "slug": {
      "title": "Slug",
      "description": "Applies to core extensions only. It declares where the extension documentation lives in the standard docs, i.e.  a `location` slug means the relevant information will be at http://standard.open-contracting.org/*version*/*lang*/extensions/location.",
      "type": "string"
    },
    "url": {
      "title": "Extension URL",
      "description": "Location of extension.json file, typically within a github repository containing the extending schema files",
      "type": "string",
      "format": "uri",
      "pattern": "^.+/extension.json"
    }
  }
}

=== RegulEsteban/extension_registry/process_title/entry.json
{
    "category": "release", 
    "documentationUrl": {
        "en": "https://github.com/open-contracting/ocds_process_title_extension/blob/master/README.md"
    },
    "name": {
        "en": "Process level title and description"
    }, 
    "core": true, 
    "url": "https://raw.githubusercontent.com/open-contracting/ocds_process_title_extension/master/extension.json", 
    "active": true, 
    "slug": "process_title", 
    "description": {
        "en": "For providing overall process titles and descriptions, often to give a free-text summary of the contracting process as a whole."
    }
}

=== RegulEsteban/extension_registry/enquiries/entry.json
[{
    "category": "tender", 
    "documentationUrl": {
        "en": "https://github.com/open-contracting/ocds_enquiry_extension/blob/master/README.md"
    },
    "name": {
        "en": "Enquiries"
    }, 
    "core": true, 
    "url": "https://raw.githubusercontent.com/open-contracting/ocds_enquiry_extension/master/extension.json", 
    "active": true, 
    "slug": "enquiries", 
    "description": {
        "en": "The enquiries extension can be used to record questions raised during a contracting process, and the answers provided."
    }
}]

=== RegulEsteban/extension_registry/additionalContactPoint/entry.json
[{
    "category": "parties", 
    "documentationUrl": {
        "en": "https://github.com/open-contracting/ocds_additionalContactPoints_extension/blob/master/README.md"
    },
    "name": {
        "en": "Additional Contact Points"
    }, 
    "core": false, 
    "url": "https://raw.githubusercontent.com/open-contracting/ocds_additionalContactPoints_extension/master/extension.json", 
    "active": true, 
    "slug": "additionalContactPoint", 
    "description": {
        "en": "For including extra contact points on each organization. Particularly useful when each contact point deals only in a particular language or group of languages."
    }
}]

=== RegulEsteban/extension_registry/risk_allocation/entry.json
[{
  "name": {
    "en" : "Risk Allocation"
  },
  "description": {
    "en": "Draft risk allocation extension for ppp extension"
  },
  "url": "https://raw.githubusercontent.com/open-contracting/ocds-riskAllocation-extension/master/extension.json",
  "documentationUrl": {
    "en": "https://github.com/open-contracting/ocds-riskAllocation-extension"
  },
  "active": true,
  "core": false,
  "category": "ppp",
  "slug": "risk_allocation"
}]

=== RegulEsteban/extension_registry/participation_fee/entry.json
[{
    "category": "tender", 
    "documentationUrl": {
        "en": "https://github.com/open-contracting/ocds_participationFee_extension/blob/master/README.md"
    },
    "name": {
        "en": "Participation Fees"
    }, 
    "core": true, 
    "url": "https://raw.githubusercontent.com/open-contracting/ocds_participationFee_extension/master/extension.json",
    "active": true, 
    "slug": "participation_fee", 
    "description": {
        "en": "Where a tender process involves payment of fees to access documents, submit a proposal, or be awarded a contract, this extension can be used to provide fee details."
    }
}]

=== RegulEsteban/extension_registry/buyer_per_contract/entry.json
{
  "name": {
    "en" : "Multiple buyers - contract level"
  },
  "description": {
    "en": "In some cases, a single contracting process involves multiple buyers (for example, a framework that different organisations can buy from). In these cases, the multiple buyers extension can be used to specify a distinct buyer for each contract."
  },
  "url": "https://raw.githubusercontent.com/open-contracting/ocds_multiple_buyers_extension/master/extension.json",
  "documentationUrl": {
    "en": "https://github.com/open-contracting/ocds_multiple_buyers_extension"
  },
  "active": true,
  "core": false,
  "category": "1.1",
  "slug": "contract"
}

=== RegulEsteban/extension_registry/bids/entry.json
{
    "category": "bids", 
    "documentationUrl": {
        "en": "https://github.com/open-contracting/ocds_bid_extension/blob/master/README.md"
    },
    "name": {
        "en": "Bid statistics and details"
    }, 
    "core": true, 
    "url": "https://raw.githubusercontent.com/open-contracting/ocds_bid_extension/master/extension.json", 
    "active": true, 
    "slug": "bids", 
    "description": {
        "en": "Allowing bid statistics, and detailed bid information to be represented."
    }
}
