=== RegulEsteban/extension_registry/entry-schema.json
{
  "id": "http://example.com",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Schema for an entry in the Open Contracting Extension Registry",
  "description": "Schema for an entry.json file pointing to the location of the extension.",
  "type": "object",
  "required": [
    "active",
    "category",
    "core",
    "description",
    "documentationUrl",
    "name",
    "url"
  ],
  "additionalProperties": false,
  "properties": {
    "active": {
      "title": "Active",
      "description": "Extension active/inactive status.",
      "type": "boolean"
    },
    "category": {
      "title": "Category",
      "description": "Part of the docs the extensions appears in.",
      "type": "string"
    },
    "core": {
      "title": "Core extension",
      "description": "Whether the extension is a core extension documented in the main docs.",
      "type": "boolean"
    },
    "dependencies": {
      "title": "Dependencies",
      "description": "Extensions this extension depends on.",
      "type": "array",
      "items":{
        "type": "string",
        "format": "uri",
        "pattern": "^.+/extension.json"
      }
    },
    "description": {
      "title": "Description",
      "description": "Description of the extensions as an object with keys being language codes (ISO 639-1) and values the description in that language.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^(ad|ae|af|ag|ai|al|am|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bl|bm|bn|bo|bq|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cu|cv|cw|cx|cy|cz|de|dj|dk|dm|do|dz|ec|ee|eg|eh|en|er|es|et|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mf|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sk|sl|sm|sn|so|sr|ss|st|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tr|tt|tv|tw|tz|ua|ug|um|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|za|zm|zw)$": {
          "type": "string"
        }
      }
    },
    "documentationUrl": {
      "title": "Documentation URL" ,
      "description": "Location of the documentation for the extension as an object with keys being language codes (ISO 639-1) and values the url of the documentation in that language.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^(ad|ae|af|ag|ai|al|am|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bl|bm|bn|bo|bq|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cu|cv|cw|cx|cy|cz|de|dj|dk|dm|do|dz|ec|ee|eg|eh|en|er|es|et|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mf|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sk|sl|sm|sn|so|sr|ss|st|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tr|tt|tv|tw|tz|ua|ug|um|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|za|zm|zw)$": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "name": {
      "title": "Name",
      "description": "Name of the extension as an object with keys being language codes (ISO 639-1) and values the name in that language",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^(ad|ae|af|ag|ai|al|am|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bl|bm|bn|bo|bq|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cu|cv|cw|cx|cy|cz|de|dj|dk|dm|do|dz|ec|ee|eg|eh|en|er|es|et|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mf|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sk|sl|sm|sn|so|sr|ss|st|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tr|tt|tv|tw|tz|ua|ug|um|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|za|zm|zw)$": {
          "type": "string"
        }
      }
    },
    "slug": {
      "title": "Slug",
      "description": "Applies to core extensions only. It declares where the extension documentation lives in the standard docs, i.e.  a `location` slug means the relevant information will be at http://standard.open-contracting.org/*version*/*lang*/extensions/location.",
      "type": "string"
    },
    "url": {
      "title": "Extension URL",
      "description": "Location of extension.json file, typically within a github repository containing the extending schema files",
      "type": "string",
      "format": "uri",
      "pattern": "^.+/extension.json"
    }
  }
}

=== RegulEsteban/extension_registry/milestone_documents/entry.json
[{
    "category": "milestones", 
    "documentationUrl": {
        "en": "https://github.com/open-contracting/ocds_milestone_documents_extension/blob/master/README.md"
    },
    "name": {
        "en": "Milestone documents"
    }, 
    "core": true,
    "url": "https://raw.githubusercontent.com/open-contracting/ocds_milestone_documents_extension/master/extension.json",
    "active": true, 
    "slug": "milestone_documents", 
    "description": {
        "en": "Documents at the milestone level were deprecated in OCDS 1.1. This extension re-introduces the ability to attach documents to each individual milestone."
    }
}]

=== RegulEsteban/extension_registry/budget_breakdown/entry.json
{
  "name": {
    "en" : "Budget breakdown"
  },
  "description": {
    "en": "For providing a detailed budget breakdown."
  },
  "url": "https://raw.githubusercontent.com/open-contracting/ocds_budget_breakdown_extension/master/extension.json",
  "documentationUrl": {
    "en":"https://github.com/open-contracting/ocds_budget_breakdown_extension/blob/master/README.md"
  },
  "active": true,
  "core": false,
  "category": "ppp, 1.1",
  "slug": "budget"
}

=== RegulEsteban/extension_registry/contract_suppliers/entry.json
[{
    "category": "contract", 
    "documentationUrl": {
        "en": "https://github.com/open-contracting/ocds_contract_suppliers_extension/blob/master/README.md"
    },
    "name": {
        "en": "Contract suppliers"
    }, 
    "core": false, 
    "url": "https://raw.githubusercontent.com/open-contracting/ocds_contract_suppliers_extension/master/extension.json", 
    "active": true, 
    "slug": "contract_suppliers", 
    "description": {
        "en": "To allow explicit declaration of suppliers within the contracts block. Used when a single award to multiple suppliers results in multiple contracts to a sub-set of those awarded suppliers."
    }
}]

=== RegulEsteban/extension_registry/metrics/entry.json
{
  "name": {
    "en" : "Metrics"
  },
  "description": {
    "en": "The metrics extension supports publication of forecasts (planning stage), targets (tender stage), agreed performance targets (award and contract stage) and results (implementation stage).."
  },
  "url": "https://raw.githubusercontent.com/open-contracting/ocds_metrics_extension/master/extension.json",
  "documentationUrl": {
    "en": "https://github.com/open-contracting/ocds_metrics_extension"
  },
  "active": true,
  "core": false,
  "category": "ppp",
  "slug": "metrics"
}

=== RegulEsteban/extension_registry/transactions_relatedMilestones/entry.json
{
  "name": {
    "en" : "Transactions - Related Milestones"
  },
  "description": {
    "en": "Adds a relatedImplementationMilestone property to the transactions object so that disbursements can be linked with their associated milestone."
  },
  "url": "https://raw.githubusercontent.com/open-contracting/ocds_transactions_relatedMilestone_extension/master/extension.json",
  "documentationUrl": {
    "en": "https://github.com/open-contracting/ocds_transactions_relatedMilestone_extension"
  },
  "active": true,
  "core": false,
  "category": "ppp",
  "slug": "transaction_milestones"
}

=== RegulEsteban/extension_registry/requirements/entry.json
[{
  "name": {
    "en" : "Requirements"
  },
  "description": {
    "en": "The requirements extension is based on the EU's Core Criterion and Core Evidence Vocabulary (CCCEV) model for communicating criteria and responses. The extension is designed to allow procuring entities or buyers to express criteria, relating to either items being procured or bidders themselves, as structured data."
  },
  "url": "https://raw.githubusercontent.com/open-contracting/ocds_requirements_extension/master/extension.json",
  "documentationUrl": {
    "en": "https://github.com/open-contracting/ocds_requirements_extension/blob/master/README.md"
  },
  "active": true,
  "core": false,
  "category": "tender",
  "slug": "requirements"
}]

=== RegulEsteban/extension_registry/lots/entry.json
{
    "category": "tender", 
    "documentationUrl": {
        "en": "https://github.com/open-contracting/ocds_lots_extension/blob/master/README.md"
    },
    "name": {
        "en": "Lots"
    }, 
    "core": true, 
    "url": "https://raw.githubusercontent.com/open-contracting/ocds_lots_extension/master/extension.json",
    "active": true, 
    "slug": "lots", 
    "description": {
        "en": "A tender process may be divided into lots, where bidders can bid on one or more lots. Details of each lot can be provided here. Items, documents and other features can then reference the lot they are related to using relatedLot. Where no relatedLot identifier is given, the values should be interpreted as applicable to the whole tender."
    }
}

=== RegulEsteban/extension_registry/location/entry.json
[{
  "name": {
    "en" : "Location"
  },
  "description": {
    "en": "Allow the point of delivery for a given item or the site of works to be completed to be indicated in both the tender, award and contract stage."
  },
  "url": "https://raw.githubusercontent.com/open-contracting/ocds_location_extension/master/extension.json",
  "documentationUrl": {
    "en": "https://github.com/open-contracting/ocds_location_extension/blob/master/README.md"
  },
  "active": true,
  "core": true,
  "category": "item",
  "slug": "location"
}]
